"""
One demo session per tester: their own database and their own transcript.

WHY
===
The shared demo link used one database and one transcript for everyone.
That caused two problems, both found by reading the code before a group of
people tested at once:

  1. One tester's booking took the slot the next tester was told to book,
     so the demo needed resetting by hand between people.
  2. The transcript was a single list cleared at the start of every call.
     Two people calling at the same time wiped each other's transcript and
     then watched each other's conversation appear.

The page now keeps a random session id in the browser. Each id gets a copy
of a freshly seeded database and its own transcript, so a tester can book
on one call and cancel on the next, and nobody else sees or affects it.

The template database is rebuilt when the date changes, because seed data
is relative to the day it is built. A session built yesterday is rebuilt
too, so nobody is offered a slot that is now in the past.
"""

from __future__ import annotations

import re
import shutil
import threading
import time
import uuid
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

from . import clock, config, db

# Generated by the page. Checked strictly because it becomes a file name.
SESSION_ID = re.compile(r"^[A-Za-z0-9-]{8,64}$")

# Enough for a shared demo link. The least recently used session goes first.
MAX_SESSIONS = 100


def valid_session_id(value: str | None) -> bool:
    return bool(value) and bool(SESSION_ID.match(value))


@dataclass
class Session:
    id: str
    events: list[dict] = field(default_factory=list)
    db_path: Path | None = None
    built_on: date | None = None
    last_used: float = field(default_factory=time.monotonic)
    # An open typed conversation, see text_chat.py.
    chat: object | None = None

    def end_chat(self) -> None:
        if self.chat is not None:
            self.chat.close()
            self.chat = None


class SessionStore:
    """Hands each tester their own database copy and transcript."""

    def __init__(self, folder: Path | str | None = None, max_sessions: int = MAX_SESSIONS, today=None):
        self.folder = Path(folder or config.DATA_DIR / "sessions")
        self.max_sessions = max_sessions
        self._today = today or clock.today
        self._sessions: dict[str, Session] = {}
        self._lock = threading.Lock()
        self._template_day: date | None = None
        self._copies = 0

    # -- public -----------------------------------------------------------

    def get(self, session_id: str | None) -> Session:
        """
        The session for this id, created if new.

        An id that is missing or malformed gets a throwaway session of its
        own, never somebody else's and never the shared database.
        """
        if not valid_session_id(session_id):
            session_id = uuid.uuid4().hex
        with self._lock:
            session = self._sessions.get(session_id)
            if session is None:
                session = Session(session_id)
                self._sessions[session_id] = session
                self._evict()
            session.last_used = time.monotonic()
            return session

    def find(self, session_id: str | None) -> Session | None:
        """An existing session, without creating one."""
        if not valid_session_id(session_id):
            return None
        with self._lock:
            return self._sessions.get(session_id)

    def database(self, session: Session) -> Path:
        """This session's database, built on first use or when a new day starts."""
        with self._lock:
            today = self._today()
            if session.db_path is None or session.built_on != today or not session.db_path.exists():
                self._copy_template(session, today)
            return session.db_path

    def reset(self, session: Session) -> Path:
        """Start this tester again from freshly seeded data."""
        with self._lock:
            session.end_chat()
            session.events.clear()
            self._copy_template(session, self._today())
            return session.db_path

    def record(self, session: Session, event: dict) -> None:
        session.events.append(event)

    # -- internals, called with the lock held ------------------------------

    def _template(self, today: date) -> Path:
        path = self.folder / "template.db"
        if self._template_day != today or not path.exists():
            self.folder.mkdir(parents=True, exist_ok=True)
            building = self.folder / "template.building.db"
            db.reset_database(building).close()
            building.replace(path)
            self._template_day = today
        return path

    def _copy_template(self, session: Session, today: date) -> None:
        old = session.db_path
        # A new file name each time rather than overwriting. On Windows a
        # database still open by a call in progress cannot be replaced, and
        # that call should finish on the data it started with.
        self._copies += 1
        session.db_path = self.folder / f"session-{session.id}-{self._copies}.db"
        shutil.copyfile(self._template(today), session.db_path)
        session.built_on = today
        if old is not None:
            _remove_quietly(old)

    def _evict(self) -> None:
        while len(self._sessions) > self.max_sessions:
            oldest = min(self._sessions.values(), key=lambda s: s.last_used)
            del self._sessions[oldest.id]
            oldest.end_chat()
            if oldest.db_path is not None:
                _remove_quietly(oldest.db_path)

    def clear_leftovers(self) -> None:
        """
        Session files from a previous run of the server belong to nobody now.

        Called when the server starts, never from the constructor: importing
        voice_app builds a store, and a test doing that would otherwise
        delete the files of a server that is running.
        """
        if self.folder.exists():
            for path in self.folder.glob("session-*.db"):
                _remove_quietly(path)


def _remove_quietly(path: Path) -> None:
    try:
        path.unlink()
    except OSError:
        # Still open by a call in progress. Cleared on the next start.
        pass
